Broadcasting in python with help of numpy 

The art of not copyig data

Cnetering array technique 

In [2]:
import numpy as np 

In [5]:
x = np.array([[10],
             [20],
             [30]])


In [6]:
x

array([[10],
       [20],
       [30]])

In [12]:
m = np.arange(1, 4)

In [13]:
m

array([1, 2, 3])

In [16]:
m.shape

(3,)

In [18]:
m.reshape(1,3)

array([[1, 2, 3]])

In [19]:
x+m 

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])