Scenario: Find patients with (Heart Rate > 100) AND (Oxygen < 90).

In [1]:
import numpy as np

# Columns: [Patient_ID, Heart_Rate, Oxygen_Level]
# ID is just a number here for simplicity
patient_data = np.array([
    [101, 72, 98],   # Healthy
    [102, 115, 90],  # High HR, but Oxygen OK
    [103, 60, 99],   # Healthy
    [104, 120, 85],  # CRITICAL: High HR + Low Oxygen
    [105, 55, 88],   # CRITICAL: Low HR + Low Oxygen
    [106, 250, 98]   # SENSOR ERROR (Heart rate 250? Unlikely)
])

In [5]:
heart_rate = patient_data[: , 1]
heart_rate

array([ 72, 115,  60, 120,  55, 250])

In [6]:
oxygen = patient_data[: , 2]
oxygen


array([98, 90, 99, 85, 88, 98])

In [7]:
masking = (heart_rate > 100 ) & (oxygen < 90)

In [10]:
print(f"Super Critical patient :  {patient_data[masking]}")


Super Critical patient :  [[104 120  85]]


Data Cleaning for negative values

In [11]:
products = np.array([
    [500, 4.5],
    [0, 3.2],     # ERROR: Price 0
    [1200, 4.0],
    [-99, 1.0],   # ERROR: Negative Price
    [300, 4.8]
])

In [12]:
prices = products[:, 0]

In [13]:
prices

array([ 500.,    0., 1200.,  -99.,  300.])

In [14]:
valid_mask = prices >0

In [15]:
valid_mask

array([ True, False,  True, False,  True])

In [17]:
cleaned_data = products[valid_mask]

In [18]:
print(f"Cleaned Deal Data : {cleaned_data}")

Cleaned Deal Data : [[ 500.     4.5]
 [1200.     4. ]
 [ 300.     4.8]]
