In [15]:
import numpy as np 

In [16]:
signal = np.array([2,4,6,8,10])
kernal= np.array([1,0,-1])


In [17]:
output = []
for i in range (len(signal)-len(kernal)+1):
    output.append(np.sum(signal[i:i+3]*kernal))

print(output)

[np.int64(-4), np.int64(-4), np.int64(-4)]


In [21]:
import numpy as np

# 1. Define the Image (5x5)
image = np.array([
    [10, 10, 10, 0, 0],
    [10, 10, 10, 0, 0],
    [10, 10, 10, 0, 0],
    [10, 10, 10, 0, 0],
    [10, 10, 10, 0, 0]
])

# 2. Define the Kernel (3x3 Vertical Edge Detector)
kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

# 3. Create an empty Output Matrix
# Output size = (Image Size - Kernel Size) + 1
# 5 - 3 + 1 = 3. So we need a 3x3 output.
output = np.zeros((3, 3))

# --- YOUR MISSION STARTS HERE ---
# Write the nested loops to slide the window.
# Hint: You need to iterate through rows (i) and columns (j) of the output.
# Inside the loop, slice the 'image' to get the current 3x3 patch.
# Then multiply that patch by the kernel and sum it up.

# TODO: Write the logic here
for i in range(output.shape[0]): 
    for j in range(output.shape[1]):
        patch = image[i:i+3, j:j+3]
        output[i, j] = np.sum(patch * kernel)
        print(patch * kernel)
        print("-----")
        print(output)
        print("-----")
        print("-----")
        print("-----")

# --- YOUR MISSION ENDS HERE ---

print("Feature Map (Output):")
print(output)

[[ 10   0 -10]
 [ 10   0 -10]
 [ 10   0 -10]]
-----
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-----
-----
-----
[[10  0  0]
 [10  0  0]
 [10  0  0]]
-----
[[ 0. 30.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
-----
-----
-----
[[10  0  0]
 [10  0  0]
 [10  0  0]]
-----
[[ 0. 30. 30.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
-----
-----
-----
[[ 10   0 -10]
 [ 10   0 -10]
 [ 10   0 -10]]
-----
[[ 0. 30. 30.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
-----
-----
-----
[[10  0  0]
 [10  0  0]
 [10  0  0]]
-----
[[ 0. 30. 30.]
 [ 0. 30.  0.]
 [ 0.  0.  0.]]
-----
-----
-----
[[10  0  0]
 [10  0  0]
 [10  0  0]]
-----
[[ 0. 30. 30.]
 [ 0. 30. 30.]
 [ 0.  0.  0.]]
-----
-----
-----
[[ 10   0 -10]
 [ 10   0 -10]
 [ 10   0 -10]]
-----
[[ 0. 30. 30.]
 [ 0. 30. 30.]
 [ 0.  0.  0.]]
-----
-----
-----
[[10  0  0]
 [10  0  0]
 [10  0  0]]
-----
[[ 0. 30. 30.]
 [ 0. 30. 30.]
 [ 0. 30.  0.]]
-----
-----
-----
[[10  0  0]
 [10  0  0]
 [10  0  0]]
-----
[[ 0. 30. 30.]
 [ 0. 30. 30.]
 [ 0. 30. 30.]]
-----
-----
-----
Feature Map (Output