We have a stream of incoming patient vitals. we don't care about the healthy ones right now. We need to instantly isolate the Critical patients.

In [1]:
import numpy as np 

In [2]:
# Columns: [Patient_ID, Heart_Rate, Oxygen_Level]
# ID is just a number here for simplicity
patient_data = np.array([
    [101, 72, 98],   # Healthy
    [102, 115, 90],  # High HR, but Oxygen OK
    [103, 60, 99],   # Healthy
    [104, 120, 85],  # CRITICAL: High HR + Low Oxygen
    [105, 55, 88],   # CRITICAL: Low HR + Low Oxygen
    [106, 250, 98]   # SENSOR ERROR (Heart rate 250? Unlikely)
])

In [3]:
patient_data

array([[101,  72,  98],
       [102, 115,  90],
       [103,  60,  99],
       [104, 120,  85],
       [105,  55,  88],
       [106, 250,  98]])

In [4]:
oxygen_col =patient_data[: , 2  ]

In [5]:
oxygen_col

array([98, 90, 99, 85, 88, 98])

In [6]:
ishypoxic = oxygen_col < 90

In [7]:
ishypoxic

array([False, False, False,  True,  True, False])

In [8]:
critical_patients = patient_data[ishypoxic]
critical_patients

array([[104, 120,  85],
       [105,  55,  88]])