In [1]:
import numpy as np 

In [ ]:
# [WBC , TEMP , HEART RATE]

patient_data = np.array([
    [5000, 98.6, 72],
    [11000, 102.4, 110],  # Sick patient
    [4500, 97.5, 65],
    [7000, 99.0, 80],
    [8500, 100.1, 85]
    ])

In [5]:
print(f"original shape : {patient_data.shape}")

original shape : (5, 3)


In [6]:
feature_means = patient_data.mean(axis=0)

In [8]:
print(f"Means : {feature_means}")

Means : [7200.     99.52   82.4 ]


In [9]:
print(f"Shape of Means : {feature_means.shape}")

Shape of Means : (3,)


In [10]:
centered_data = patient_data- feature_means

In [11]:
print ("centered data : ", centered_data)


centered data :  [[-2.20e+03 -9.20e-01 -1.04e+01]
 [ 3.80e+03  2.88e+00  2.76e+01]
 [-2.70e+03 -2.02e+00 -1.74e+01]
 [-2.00e+02 -5.20e-01 -2.40e+00]
 [ 1.30e+03  5.80e-01  2.60e+00]]


In [12]:
print(f"\nNew Means (should be ~0): {centered_data.mean(axis=0)}")


New Means (should be ~0): [ 0.00000000e+00 -1.13686838e-14 -5.68434189e-15]


In [13]:
std_patient_data = patient_data.std(axis=0)

In [16]:
print(std_patient_data)

[2.37907545e+03 1.66300932e+00 1.53961034e+01]


In [17]:
dividation = centered_data/std_patient_data

In [18]:
print("\nStandardized data : \n", dividation)


Standardized data : 
 [[-0.92472897 -0.55321398 -0.67549559]
 [ 1.59725914  1.73180028  1.79266138]
 [-1.13489465 -1.21466547 -1.13015609]
 [-0.08406627 -0.31268616 -0.1558836 ]
 [ 0.54643076  0.34876533  0.1688739 ]]


In [19]:
clinical_data = np.array([
    [[72, 98], [70, 99], [71, 98]],      # Patient A (Day 1, 2, 3)
    [[110, 92], [115, 90], [120, 88]]    # Patient B (Day 1, 2, 3)
])

In [21]:
weights = np.array([0.5,0.5,0.5])
weights=weights[np.newaxis, : , np.newaxis]
weighted_data = clinical_data*weights
print(weighted_data)

[[[36.  49. ]
  [35.  49.5]
  [35.5 49. ]]

 [[55.  46. ]
  [57.5 45. ]
  [60.  44. ]]]


In [22]:
clinical_data

array([[[ 72,  98],
        [ 70,  99],
        [ 71,  98]],

       [[110,  92],
        [115,  90],
        [120,  88]]])

In [23]:
import numpy as np

clinical_data = np.array([
    [[72, 98], [70, 99], [71, 98]],
    [[110, 92], [115, 90], [120, 88]]
])

# Step 1 — Max subtraction (Numerical Stabilization)
max_vals = clinical_data.max(axis=2, keepdims=True)
result = clinical_data - max_vals        # shifted values


In [24]:
max_vals

array([[[ 98],
        [ 99],
        [ 98]],

       [[110],
        [115],
        [120]]])

In [25]:
clinical_data

array([[[ 72,  98],
        [ 70,  99],
        [ 71,  98]],

       [[110,  92],
        [115,  90],
        [120,  88]]])

In [26]:
result

array([[[-26,   0],
        [-29,   0],
        [-27,   0]],

       [[  0, -18],
        [  0, -25],
        [  0, -32]]])

In [28]:
exp_val = np.exp(result)
exp_val


array([[[5.10908903e-12, 1.00000000e+00],
        [2.54366565e-13, 1.00000000e+00],
        [1.87952882e-12, 1.00000000e+00]],

       [[1.00000000e+00, 1.52299797e-08],
        [1.00000000e+00, 1.38879439e-11],
        [1.00000000e+00, 1.26641655e-14]]])

In [29]:
sum_exp = exp_val.sum(axis=2 , keepdims=True)
sum_exp

array([[[1.        ],
        [1.        ],
        [1.        ]],

       [[1.00000002],
        [1.        ],
        [1.        ]]])

In [30]:
softmax_output = exp_val / sum_exp

In [31]:
softmax_output

array([[[5.10908903e-12, 1.00000000e+00],
        [2.54366565e-13, 1.00000000e+00],
        [1.87952882e-12, 1.00000000e+00]],

       [[9.99999985e-01, 1.52299795e-08],
        [1.00000000e+00, 1.38879439e-11],
        [1.00000000e+00, 1.26641655e-14]]])