In [2]:
import numpy as np 

In [2]:
import array 

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
np.array([3.0, 3,4,6])

array([3., 3., 4., 6.])

In [6]:
np.array([1,2.9,4,7.0])

array([1. , 2.9, 4. , 7. ])

In [7]:
np.array([1,2,3,45], dtype=np.float32)

array([ 1.,  2.,  3., 45.], dtype=float32)

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
arr = np.zeros(10, dtype=np.int32)
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [18]:
np.ones((3,5), dtype=np.float32)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [19]:
np.full((3,7), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
x = np.arange(4)
x


array([0, 1, 2, 3])

In [5]:
print ( "X : " ,x)

X :  [0 1 2 3]


In [6]:
print ('x+5 : ', x+5)

x+5 :  [5 6 7 8]


In [9]:
print ('x-5 : ', x-5)
x

x-5 :  [-5 -4 -3 -2]


array([0, 1, 2, 3])

In [10]:
print('x//2     : ', x//2)

x//2     :  [0 0 1 1]
