In [1]:
import numpy as np 

In [2]:
rng = np.random.default_rng(seed=1701)
x1 = rng.integers(10, size = 6)
x2 = rng.integers(10, size = (3,4))
x3 = rng.integers(10, size=(3,4,5))



In [3]:
x1

array([9, 4, 0, 3, 8, 6])

In [4]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [5]:
x3

array([[[4, 3, 5, 5, 0],
        [8, 3, 5, 2, 2],
        [1, 8, 8, 5, 3],
        [0, 0, 8, 5, 8]],

       [[5, 1, 6, 2, 3],
        [1, 2, 5, 6, 2],
        [5, 2, 7, 9, 3],
        [5, 6, 0, 2, 0]],

       [[2, 9, 4, 3, 9],
        [9, 2, 2, 4, 0],
        [0, 3, 0, 0, 2],
        [3, 2, 7, 4, 7]]])

In [6]:
print(x3.ndim)

3


In [7]:
print(x3.shape)

(3, 4, 5)


In [8]:
print(x3.size)

60


In [9]:
print(x3.dtype)

int64


Array Indexing 


In [10]:
x1[0]

np.int64(9)

In [11]:
print(x1[0])

9


In [12]:
print(x1[-1])

6


In [14]:
print(x2[1,2])

2


In [21]:
grid = np.arange(1,10).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
x = np.array([2,3,5])

In [23]:
x

array([2, 3, 5])

In [24]:
x.reshape(1,3)

array([[2, 3, 5]])

In [25]:
x.reshape(3,1)

array([[2],
       [3],
       [5]])

In [26]:
x

array([2, 3, 5])

In [27]:
x = np.array([1,2,3])

In [28]:
y = np.array([4,5,6])

In [29]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [30]:
z = np.array([7,5,3])

In [31]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 5, 3])

In [42]:
m = np.random.randint(0,10, size=(3,4))


In [43]:
m

array([[1, 1, 9, 1],
       [7, 9, 3, 5],
       [3, 7, 4, 8]], dtype=int32)

In [44]:
n= np.random.randint(1,10,size=(3,4))

In [45]:
n

array([[3, 1, 2, 1],
       [2, 4, 8, 3],
       [4, 6, 9, 4]], dtype=int32)

In [46]:
np.concatenate([m,n])

array([[1, 1, 9, 1],
       [7, 9, 3, 5],
       [3, 7, 4, 8],
       [3, 1, 2, 1],
       [2, 4, 8, 3],
       [4, 6, 9, 4]], dtype=int32)

In [47]:
np.concatenate([m,m])

array([[1, 1, 9, 1],
       [7, 9, 3, 5],
       [3, 7, 4, 8],
       [1, 1, 9, 1],
       [7, 9, 3, 5],
       [3, 7, 4, 8]], dtype=int32)

In [49]:
np.concatenate([m,m],axis=1)


array([[1, 1, 9, 1, 1, 1, 9, 1],
       [7, 9, 3, 5, 7, 9, 3, 5],
       [3, 7, 4, 8, 3, 7, 4, 8]], dtype=int32)

In [ ]:
np.concatenate([m,m],axis=0)x 

array([[1, 1, 9, 1],
       [7, 9, 3, 5],
       [3, 7, 4, 8],
       [1, 1, 9, 1],
       [7, 9, 3, 5],
       [3, 7, 4, 8]], dtype=int32)

In [52]:
x

array([1, 2, 3])

In [54]:
p = np.random.randint(1,10,size=(3,3))

In [55]:
p

array([[8, 5, 7],
       [1, 4, 4],
       [5, 1, 4]], dtype=int32)

In [57]:
np.vstack([x,p])

array([[1, 2, 3],
       [8, 5, 7],
       [1, 4, 4],
       [5, 1, 4]])

In [58]:
x = np.array([1,2,3,99,99,4,5,6])

In [59]:
x

array([ 1,  2,  3, 99, 99,  4,  5,  6])

In [60]:
x1,x2,x3 = np.split(x,[3,5])

In [61]:
print(x1,x2,x3)

[1 2 3] [99 99] [4 5 6]
